### PR TITLE
Add new 'folder' type to element option settings

### PR DESCRIPTION
**Pull request by davidpede**
### What does it do?
Adds a new element setting type for folders. Use like: 
```
{
  "remote": true,
  "settings": [
    {
      "name": "folder_path",
      "label": "Select a Folder",
      "type": "folder",
      "mediaSource": "myMediaSource",
      "value": ""
    }
  ]
}

```

### Why is it needed?
Adds support for elements that require a folder path rather than a file path such as galleries.

### CODE REVIEW

**Comment by theboxer** [comment]
Merged in 94954c08eb4ce559c0cf8e67ac5f807487bc781c.

Thank you for this one, it's a nice addition :)

Btw. I added a small tweak, the elFinder won't show files when you want to select only folders.

**Comment by davidpede** [comment]
Thanks looks good

**Comment by davidpede** [comment]
@theboxer Sorry I know this was closed but could we make the change you made optional? Got feedback from users that they now can't see whats in the folders so don't know which to select etc. Something like:

```
{
  "settings": [
    {
      "name": "folder_path",
      "label": "Select a Folder",
      "type": "folder",
      "showFiles": 1 //or 0 (default)
      "mediaSource": "myMediaSource",
      "value": ""
    }
  ]
}
```

**Comment by theboxer** [comment]
Added `showOnlyFolders` option, by default it's false

**Pull request closed without merging**
